name: site-speed-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - beautifulsoup4
  - pandas
  - matplotlib
  - seaborn
  - xgboost
  - imbalanced-learn
  - streamlit